title: Jordi Bayer's portfolio
email: jordi.be.1992@gmail.com
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
url: "https://www.linkedin.com/in/jordibayerespinosa/"
github_username:  jordibayer
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
